### ISSUE TITLE
Interesting facts you should add to your femboy website 💯 

### ISSUE THREAD

**Issue by 8dcc** [Sugaryyyy/Sugaryyyy.github.io#1]
Hello I see you are going through a difficult time in your life, but it's okay. Here are some interesting facts you should add to the website.

### Source of Heat

The sun is the only thing that prevents our planet from being too cold to sustain life. Without the sun’s heat, life would be impossible on earth. If you examine the temperature of the fourth planet in our solar system (Mars), which is around 128 million miles away from the sun (compared to Earth’s average of 91 million), the average temperature is around -80 degrees F (-60 degrees C), though these temperatures can plummet much further at night and in winter. If one considers the fact that a human cannot survive if their body temperature drops below 21 degrees C, one can see how life would be impossible in such cold conditions, and the importance of the sun’s heat to Earth. This heat also ensures that water on earth is available in liquid form (as apposed to frozen water or steam).

### Energy Resource

The sun's heat also creates a vast amount of energy on our planet, in fact, pretty much all energy created and used on Earth derives from the sun in one way or another. Many people are aware of harnessing solar energy to create power, but the Sun is also the main cause of the weather patterns and air currents we experience on our planet. This is then harnessed as energy by turbines in the form of wind turbines or marine energy (from the ocean). The sun also causes an evaporation of water that creates rainfall, which is collected and converted to power by large dams (known as hydropower).

When answering the question – why do we need the sun to survive? One should not disregard the importance of energy and power to modern day life on the planet. From agriculture to all modern conveniences, energy is required for almost everything in today’s world. Though the most common form of energy used in Earth today is in the form of fossil fuels, this energy still originally derives from sunlight.

### Photosynthesis: Oxygen and Food

Another way energy is harvested by the sun is in the form of photosynthesis. This process is done by plants and other autotrophic organisms and is essential for all life on Earth. Photosynthesis involves sunlight being converted into glucose, a by-product of which is oxygen. Whilst it is obvious to most that life would be impossible on Earth without oxygen, the process of photosynthesis is also essential for food on this planet, meaning that if plants were not able to perform this action and grow and flourish, the entire food chain would suffer and no animal would have food, including us humans.

### Gravity and the Perfect Distance

Our planet, and every other planet in our solar system, revolves around the sun. Our orbit of the sun lasts for 365 days, and a complete orbit forms a year on Earth. This orbital effect is caused by the sun’s large gravitational pull, and our orbit ensures that we consistently remain at the perfect distance from the sun to reap the benefits and not experience temperatures that are either too hot or too cold for the existence of life on Earth. When ascertaining an answer to the question – why do we need the sun to survive? The fact that we are constantly revolving around it, at the perfect distance, is a key fact to consider.

### Light

The sun is the main source of light on the planet, and ensures that all creatures are able to see throughout the day. Without this light it would be very difficult to do things necessary for life, such as attain food, as they would be unable to see anything. It could be argued, however, that all life would have evolved to use other means of navigation and detection, much like animals who dwell in dark areas (like caves) or nocturnal hunters. That being said, the light provided by the sun makes the possibility of life far easier.

### Vitamin D Production

When a human is exposed to safe levels of UV light (which is formed by the sun but can also be created artificially), it causes one’s body to produce Vitamin D via a metabolic process which is instigated from UV light (specifically UVB) hitting one’s skin. The main purpose of vitamin D is to help the body to absorb calcium, ensuring for strong bones, though it is known to have many other positive effects on the body. Whilst this may not be an absolute necessity for life to be possible on our planet, it does help to ensure that life (for humans at least) is healthy, strong, and able to flourish. It should be stated, however, that over exposure to UV light can cause damaging and potentially life threatening complications. That is why wearing sunscreens to block harmful radiation is very important.

### Conclusion

One should now have a clear answer to the question – why do we need the sun to survive? As one can ascertain from the information detailed herein, the sun provides numerous benefits to earth, many of which are absolutely essential for life to exist. Without the sun we would not be shrouded in darkness, rather, we wouldn't be here at all.

**Comment by Gogo268** [comment]
thank you for the hot PC TUTORIALE on what sun is, but sadly it's possibly unrelated to the whole point of the website.

**Comment by Sugaryyyy** [comment]
what even

**Comment by 8dcc** [comment]
> thank you for the hot PC TUTORIALE on what sun is, but sadly it's possibly unrelated to the whole point of the website.

You don't get it.
